### ISSUE TITLE
How to use Guzzle MockHandler with the Guzzle 6 Factory

### ISSUE THREAD

**Issue by rrajkomar** [php-http/HttplugBundle#279]
The is no documentation on we can use a specific handler from the configuration of a guzzle 6 client.
Guzzle Client intanciation has an "handler" option but I can't find how to use it from the bundle.

Any help would be appreciated.

**Comment by dbu** [comment]
to use custom configuration on guzzle but still profit from the httplug web client debug toolbar integration, configure the guzzle6 service as you need it, configure a service with the guzzle6 adapter (not using the factory but directly the class and inject the guzzle6 client to it) and then configure a httplug client with the `service` instead of `factory` configuration. this is documented at the end of http://docs.php-http.org/en/latest/integrations/symfony-bundle.html#configure-clients
