### ISSUE TITLE
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead

### ISSUE THREAD

**Issue by zerkms** [php-http/HttplugBundle#433]
**PHP version**: x.y.z (hint: `php --version`) 8.1.9

**Description**

At the moment `HttplugBundle` depends on `php-http/message-factory`

https://github.com/php-http/HttplugBundle/blob/7c638710c3d4d4fe14de9e28e9a98c073a289cea/composer.json#L35

which [was deprecated](https://github.com/php-http/message-factory).

**How to reproduce**

**Possible Solution**

**Additional context**

**Comment by ruudk** [comment]
@dbu I looked into this, but how is this supposed to be handled for this bundle? I think it can only be done in v2?

**Comment by dbu** [comment]
yep, we can't avoid this without a BC break.

we did prepare in https://github.com/php-http/HttplugBundle/pull/427 , exposing the psr stuff for autowiring.

i don't have much time for OS atm, but would not be oposed to people looking into a new major version and getting rid of legacy things. the current version seems really stable - it is used in quite some places and there are very little complaints. so making 2.0 should not impact 1.x users too much as not much is going on anyways.

we could weed out quite a bit of the DI configuration code, and also simplify the documentation because we don't need to explain that much deprecated stuff anymore.

**Comment by dbu** [comment]
fixed in #439, will be in version 2.

**Comment by Prometee** [comment]
Hello @dbu do you have a date to release 2.0 ? It looks like it's pretty stable, do you need help on something to release it ?

**Comment by dbu** [comment]
hi, yeah we should release soon. the one thing missing is cleaning up the code for strict typing, as that is a BC break when people extend classes. and #321 as well.

if you have some time to check that all class properties, arguments and methods are typed, that would certainly help. if you could do a pull request with it, all the better.

if not i will try to find time for it later this week.

**Comment by Prometee** [comment]
What about adding PHPStan and Easy Coding Standard (it use  PHP-CS-Fixer) to the CI ?
It will help keeping some basic rules for this repository and I think it can take care of some types requirements.

I will start creating the PR you mentioned and then see if PHPStan and ECS can be added and have any benefits.

EDIT: I didn't notice that PHP CS fixer was already used so no need for ECS, then PHPStan can be the way to detect issues with non typed properties.

**Comment by dbu** [comment]
awesome if you have time to add phpstan and fix easy issues / generate a baseline for the rest. we have it set up in https://github.com/php-http/httplug/ - if you can do it similar that will help with consistency across the repositories. :+1:
